export const projects = [
    {
        title: "Gmail Clone",
        tech: ["React", "Firebase", "Redux", "Material-UI"],
        description: "Fully responsive Gmail UI clone with auth and mail handling.",
        github: "https://github.com/harshaltribhuwan/gmail-clone",
        demo: "https://clone-ht.web.app/",
    },
    {
        title: "Movie Hunt",
        tech: ["React", "Material UI", "API Integations"],
        description: "Movie and TV show explorer with trailer support via TMDb.",
        github: "https://github.com/harshaltribhuwan/movie-hunt-react",
        demo: 'https://movie-hunt-react.netlify.app/',
    },
    {
        title: "Slack Clone",
        tech: ["React", "Redux", "Firebase"],
        description: "Real-time chat app clone styled with MUI & Firebase backend.",
        github: "https://github.com/harshaltribhuwan/slack-clone",
        demo: "https://slack-clone-ht.web.app/",
    },
    {
        title: "AI Resume Critic",
        tech: ["React", "SCSS", "Framer Motion"],
        description: "Smart PDF resume reviewer with animated feedback.",
        github: "https://github.com/harshaltribhuwan/ai-resume-critic",
        demo: "https://harshaltribhuwan.github.io/ai-resume-critic/",
    },
    {
        title: "GSAP in Motion",
        tech: ["React", "GSAP", "Tailwind css"],
        description: "Smooth animations and modern UI with GSAP, Tailwind.",
        github: "https://github.com/harshaltribhuwan/gsap-tailwind-animations",
        demo: "https://harshaltribhuwan.github.io/gsap-tailwind-animations/",
    },
    {
        title: "Flavor Finder",
        tech: ["React", "Scss", "API Integration"],
        description: "Search recipes by ingredients or dish names via API.",
        github: "https://github.com/harshaltribhuwan/recipe-finder",
        demo: "https://harshaltribhuwan.github.io/recipe-finder/",
    },
    {
        title: "Insight Board",
        tech: ["React", "Recharts", "Material UI"],
        description: "Interactive dashboard with charts and dynamic, user-friendly interface.",
        github: "https://github.com/harshaltribhuwan/dashboard-ui",
        demo: "https://dashboard-ui-task.netlify.app/",
    },
    {
        title: "FluidProfiles",
        tech: ["React", "Framer Motion", "API Integration"],
        description: "Filterable user cards with smooth transitions and interactive fluid animations.",
        github: "https://github.com/harshaltribhuwan/animated-user-explorer",
        demo: "https://harshaltribhuwan.github.io/animated-user-explorer/",
    },
    {
        title: "PixHunt",
        tech: ["React", "Tailwind", "Pixabay API"],
        description: "Image search UI using Pixabay with Tailwind styling.",
        github: "https://github.com/harshaltribhuwan/image-gallary-tailwind",
        demo: "https://image-gallary-tailwind.netlify.app/",
    },
    {
        title: "GameHub",
        tech: ["React", "Redux", "Styled Components"],
        description: "Browse and get game info using RAWG API.",
        github: "https://github.com/harshaltribhuwan/gamehub-react",
        demo: 'https://harshaltribhuwan.github.io/gamehub-react/',
    },
    {
        title: "TaskNest",
        tech: ["React", "CSS", "Local Storage"],
        description: "Simple todo app with persistent local storage.",
        github: "https://github.com/harshaltribhuwan/todo-list",
        demo: "https://harshaltribhuwan.github.io/to-do-app/",
    },
    {
        title: "OTPify",
        tech: ["React", "Framer Motion", "SASS"],
        description: "Custom OTP input field with clean UI and animation.",
        github: "https://github.com/harshaltribhuwan/react-otp-component",
        demo: 'https://harshaltribhuwan.github.io/react-otp-component/',
    },
    {
        title: "Music Player",
        tech: ["React", "SASS"],
        description: "Chillhop music player with animated waves and playlist.",
        github: "https://github.com/harshaltribhuwan/music-player-react",
        demo: "https://harshaltribhuwan.github.io/music-player-react/",
    },
    {
        title: "LinkedIn Clone",
        tech: ["React", "Redux", "Material-UI", "Firebase"],
        description: "LinkedIn-style UI clone with feed and Firebase backend.",
        github: "https://github.com/harshaltribhuwan/linkedin-clone",
        demo: null,
    },
    {
        title: "Snapchat Clone",
        tech: ["React", "Redux", "Firebase", "Material-UI"],
        description: "Snapchat clone with camera, snaps, and Firebase auth.",
        github: "https://github.com/harshaltribhuwan/snapchat-clone",
        demo: null,
    },
    {
        title: "Instagram Clone",
        tech: ["Next.js", "Firebase", "Recoil", "Tailwind"],
        description: "Instagram UI clone with posts, stories, and auth.",
        github: "https://github.com/harshaltribhuwan/instagram-clone",
        demo: null,
    },
    {
        title: "Glee Digital E-commerce",
        tech: ["MongoDB", "Express", "React", "Node.js"],
        description: "Full-stack electronics e-commerce platform (MERN).",
        github: "https://github.com/harshaltribhuwan/glee-digital-e-commerce",
        demo: null,
    },
    {
        title: "Bookstore",
        tech: ["React", "Redux", "Node.js", "MongoDB"],
        description: "MERN-based bookstore with auth and cart features.",
        github: "https://github.com/harshaltribhuwan/Bookstore",
        demo: null,
    },
];